// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(FloraHolidayContext))]
    [Migration("20251008155022_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bieding", b =>
                {
                    b.Property<int>("BiedingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BiedingId"));

                    b.Property<int>("AantalStuks")
                        .HasColumnType("int");

                    b.Property<decimal>("BedragPE")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("GebruikerNummer")
                        .HasColumnType("int");

                    b.Property<int>("VeilingNummer")
                        .HasColumnType("int");

                    b.Property<int?>("VeilingproductId")
                        .HasColumnType("int");

                    b.HasKey("BiedingId");

                    b.HasIndex("GebruikerNummer");

                    b.HasIndex("VeilingNummer");

                    b.HasIndex("VeilingproductId");

                    b.ToTable("Biedingen");
                });

            modelBuilder.Entity("Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categorieën");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerId"));

                    b.Property<int>("Assortiment")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kvk")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("LaatstIngelogd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersoneelsNr")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StraatAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GebruikerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Veiling", b =>
                {
                    b.Property<int>("VeilingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingId"));

                    b.Property<TimeSpan?>("Begintijd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Endtijd")
                        .HasColumnType("time");

                    b.Property<int>("VeilingproductNummer")
                        .HasColumnType("int");

                    b.HasKey("VeilingId");

                    b.HasIndex("VeilingproductNummer")
                        .IsUnique();

                    b.ToTable("Veilingen");
                });

            modelBuilder.Entity("Veilingproduct", b =>
                {
                    b.Property<int>("VeilingproductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingproductId"));

                    b.Property<int>("CategorieNummer")
                        .HasColumnType("int");

                    b.Property<int>("Fust")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeplaatstDatum")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Startprijs")
                        .HasColumnType("int");

                    b.Property<int>("Voorraad")
                        .HasColumnType("int");

                    b.HasKey("VeilingproductId");

                    b.HasIndex("CategorieNummer");

                    b.ToTable("Veilingproducten");
                });

            modelBuilder.Entity("Bieding", b =>
                {
                    b.HasOne("Gebruiker", "Gebruiker")
                        .WithMany("Biedingen")
                        .HasForeignKey("GebruikerNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veiling", "Veiling")
                        .WithMany()
                        .HasForeignKey("VeilingNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilingproduct", null)
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingproductId");

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("Veiling", b =>
                {
                    b.HasOne("Veilingproduct", "Veilingproduct")
                        .WithOne("veiling")
                        .HasForeignKey("Veiling", "VeilingproductNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veilingproduct");
                });

            modelBuilder.Entity("Veilingproduct", b =>
                {
                    b.HasOne("Categorie", "Categorie")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("CategorieNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Categorie", b =>
                {
                    b.Navigation("Veilingproducten");
                });

            modelBuilder.Entity("Gebruiker", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("Veilingproduct", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("veiling")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
