// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_api.Data;

#nullable disable

namespace mvc_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205162541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ROLE-CONC-1",
                            Name = "VeilingMeester",
                            NormalizedName = "VEILINGMEESTER"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "ROLE-CONC-2",
                            Name = "Klant",
                            NormalizedName = "KLANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.Property<int>("BiedNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalStuks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedragPerFust")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingproductNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("BiedNr");

                    b.HasIndex("GebruikerNr");

                    b.HasIndex("VeilingNr");

                    b.HasIndex("VeilingproductNr");

                    b.ToTable("Bieding");

                    b.HasData(
                        new
                        {
                            BiedNr = 1001,
                            AantalStuks = 5,
                            BedragPerFust = 13,
                            GebruikerNr = 2,
                            VeilingNr = 201,
                            VeilingproductNr = 101
                        },
                        new
                        {
                            BiedNr = 1002,
                            AantalStuks = 3,
                            BedragPerFust = 21,
                            GebruikerNr = 2,
                            VeilingNr = 202,
                            VeilingproductNr = 102
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CategorieNr");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            CategorieNr = 1,
                            Naam = "Tulpen"
                        },
                        new
                        {
                            CategorieNr = 2,
                            Naam = "Rozen"
                        },
                        new
                        {
                            CategorieNr = 3,
                            Naam = "Lelie"
                        },
                        new
                        {
                            CategorieNr = 4,
                            Naam = "Zonnebloem"
                        },
                        new
                        {
                            CategorieNr = 5,
                            Naam = "Chrysant"
                        },
                        new
                        {
                            CategorieNr = 6,
                            Naam = "Pioenroos"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedrijfsNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerNr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kvk")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LaatstIngelogd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<string>("StraatAdres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BedrijfsNaam = "Flora BV",
                            ConcurrencyStamp = "STATIC-CONC-1",
                            Email = "flora@example.nl",
                            EmailConfirmed = false,
                            GebruikerNr = 1,
                            Kvk = "12345678",
                            LaatstIngelogd = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NormalizedEmail = "FLORA@EXAMPLE.NL",
                            NormalizedUserName = "FLORA@EXAMPLE.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEExampleHashVoorGebruiker1++++++++++++",
                            PhoneNumberConfirmed = false,
                            Postcode = "1234AB",
                            SecurityStamp = "STATIC-USER-1",
                            Soort = "Bedrijf",
                            Status = "Active",
                            StraatAdres = "Bloemig 10",
                            TwoFactorEnabled = false,
                            UserName = "flora@example.nl"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            BedrijfsNaam = "Jan Jansen",
                            ConcurrencyStamp = "STATIC-CONC-2",
                            Email = "jan@example.nl",
                            EmailConfirmed = false,
                            GebruikerNr = 2,
                            Kvk = "00000000",
                            LaatstIngelogd = new DateTime(2025, 10, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            LockoutEnabled = false,
                            NormalizedEmail = "JAN@EXAMPLE.NL",
                            NormalizedUserName = "JAN@EXAMPLE.NL",
                            PasswordHash = "AQAAAAIAAYagAAAAEExampleHashVoorGebruiker2++++++++++++",
                            PhoneNumberConfirmed = false,
                            Postcode = "2345BC",
                            SecurityStamp = "STATIC-USER-2",
                            Soort = "Koper",
                            Status = "Active",
                            StraatAdres = "Laan 5",
                            TwoFactorEnabled = false,
                            UserName = "jan@example.nl"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Begintijd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Eindtijd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeilingNaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("VeilingNr");

                    b.ToTable("Veiling");

                    b.HasData(
                        new
                        {
                            VeilingNr = 201,
                            Begintijd = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = "active",
                            VeilingNaam = "veiling001"
                        },
                        new
                        {
                            VeilingNr = 202,
                            Begintijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = "active",
                            VeilingNaam = "veiling001"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.Property<int>("VeilingProductNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalFusten")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BeginDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategorieNr")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeplaatstDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kwekernr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimumprijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Startprijs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<int?>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoorraadBloemen")
                        .HasColumnType("INTEGER");

                    b.HasKey("VeilingProductNr");

                    b.HasIndex("Kwekernr");

                    b.HasIndex("VeilingNr");

                    b.HasIndex("CategorieNr", "Naam");

                    b.ToTable("Veilingproduct");

                    b.HasData(
                        new
                        {
                            VeilingProductNr = 101,
                            AantalFusten = 10,
                            CategorieNr = 1,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = "../../src/assets/pictures/productBloemen/DecoratieveDahliaSunsetFlare.webp",
                            Kwekernr = 1,
                            Minimumprijs = 10,
                            Naam = "Tulp Mix",
                            Plaats = "Aalsmeer",
                            Startprijs = 12,
                            Status = "Active",
                            VeilingNr = 201,
                            VoorraadBloemen = 500
                        },
                        new
                        {
                            VeilingProductNr = 102,
                            AantalFusten = 10,
                            CategorieNr = 2,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = "../../src/assets/pictures/productBloemen/EleganteTulpCrimsonGlory.webp",
                            Kwekernr = 1,
                            Minimumprijs = 15,
                            Naam = "Rode Roos",
                            Plaats = "Eelde",
                            Startprijs = 20,
                            Status = "Active",
                            VeilingNr = 202,
                            VoorraadBloemen = 300
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", "Gebruiker")
                        .WithMany("Biedingen")
                        .HasForeignKey("GebruikerNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veilingproduct", "Veilingproduct")
                        .WithMany()
                        .HasForeignKey("VeilingproductNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");

                    b.Navigation("Veilingproduct");
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.HasOne("mvc_api.Models.Categorie", "Categorie")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("CategorieNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("Kwekernr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categorie");

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Navigation("Veilingproducten");
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Veilingproducten");
                });
#pragma warning restore 612, 618
        }
    }
}
