// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_api.Data;

#nullable disable

namespace mvc_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126174613_LaatsteAanpassingen")]
    partial class LaatsteAanpassingen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.Property<int>("BiedNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalStuks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedragPerFust")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebruikerNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingproductNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("BiedNr");

                    b.HasIndex("GebruikerNr");

                    b.HasIndex("VeilingNr");

                    b.HasIndex("VeilingproductNr");

                    b.ToTable("Bieding");

                    b.HasData(
                        new
                        {
                            BiedNr = 1001,
                            AantalStuks = 5,
                            BedragPerFust = 13,
                            GebruikerNr = 2,
                            VeilingNr = 201,
                            VeilingproductNr = 0
                        },
                        new
                        {
                            BiedNr = 1002,
                            AantalStuks = 3,
                            BedragPerFust = 21,
                            GebruikerNr = 2,
                            VeilingNr = 202,
                            VeilingproductNr = 0
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CategorieNr");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            CategorieNr = 1,
                            Naam = "Tulpen"
                        },
                        new
                        {
                            CategorieNr = 2,
                            Naam = "Rozen"
                        },
                        new
                        {
                            CategorieNr = 3,
                            Naam = "Lelie"
                        },
                        new
                        {
                            CategorieNr = 4,
                            Naam = "Zonnebloem"
                        },
                        new
                        {
                            CategorieNr = 5,
                            Naam = "Chrysant"
                        },
                        new
                        {
                            CategorieNr = 6,
                            Naam = "Pioenroos"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedrijfsNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kvk")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LaatstIngelogd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StraatAdres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("GebruikerNr");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gebruiker");

                    b.HasData(
                        new
                        {
                            GebruikerNr = 1,
                            BedrijfsNaam = "Flora BV",
                            Email = "flora@example.nl",
                            Kvk = "12345678",
                            LaatstIngelogd = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "1234AB",
                            Soort = "Bedrijf",
                            StraatAdres = "Bloemig 10",
                            Wachtwoord = "***"
                        },
                        new
                        {
                            GebruikerNr = 2,
                            BedrijfsNaam = "Jan Jansen",
                            Email = "jan@example.nl",
                            Kvk = "00000000",
                            LaatstIngelogd = new DateTime(2025, 10, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "2345BC",
                            Soort = "Koper",
                            StraatAdres = "Laan 5",
                            Wachtwoord = "***"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Begintijd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Eindtijd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeilingNaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("VeilingNr");

                    b.ToTable("Veiling");

                    b.HasData(
                        new
                        {
                            VeilingNr = 201,
                            Begintijd = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = "active",
                            VeilingNaam = "veiling001"
                        },
                        new
                        {
                            VeilingNr = 202,
                            Begintijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = "active",
                            VeilingNaam = "veiling001"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.Property<int>("VeilingProductNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalFusten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieNr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeplaatstDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kwekernr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimumprijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Startprijs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoorraadBloemen")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("beginDatum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("VeilingProductNr");

                    b.HasIndex("Kwekernr");

                    b.HasIndex("VeilingNr");

                    b.HasIndex("CategorieNr", "Naam");

                    b.ToTable("Veilingproduct");

                    b.HasData(
                        new
                        {
                            VeilingProductNr = 101,
                            AantalFusten = 10,
                            CategorieNr = 1,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = "../../src/assets/pictures/productBloemen/DecoratieveDahliaSunsetFlare.webp",
                            Kwekernr = 1,
                            Minimumprijs = 10,
                            Naam = "Tulp Mix",
                            Plaats = " Aalsmeer",
                            Startprijs = 12,
                            VeilingNr = 201,
                            VoorraadBloemen = 500,
                            beginDatum = new DateOnly(1, 1, 1),
                            status = false
                        },
                        new
                        {
                            VeilingProductNr = 102,
                            AantalFusten = 10,
                            CategorieNr = 2,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = "../../src/assets/pictures/productBloemen/EleganteTulpCrimsonGlory.webp",
                            Kwekernr = 1,
                            Minimumprijs = 15,
                            Naam = "Rode Roos",
                            Plaats = "Eelde",
                            Startprijs = 20,
                            VeilingNr = 202,
                            VoorraadBloemen = 300,
                            beginDatum = new DateOnly(1, 1, 1),
                            status = false
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", "Gebruiker")
                        .WithMany("Biedingen")
                        .HasForeignKey("GebruikerNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veilingproduct", "Veilingproduct")
                        .WithMany()
                        .HasForeignKey("VeilingproductNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");

                    b.Navigation("Veilingproduct");
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.HasOne("mvc_api.Models.Categorie", "Categorie")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("CategorieNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("Kwekernr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categorie");

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Navigation("Veilingproducten");
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Veilingproducten");
                });
#pragma warning restore 612, 618
        }
    }
}
