// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_api.Data;

#nullable disable

namespace mvc_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110105840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.Property<int>("BiedNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalStuks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BedragPerFust")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("GebruikerNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("BiedNr");

                    b.HasIndex("GebruikerNr");

                    b.HasIndex("VeilingNr");

                    b.ToTable("Bieding");

                    b.HasData(
                        new
                        {
                            BiedNr = 1001,
                            AantalStuks = 5,
                            BedragPerFust = 13.50m,
                            GebruikerNr = 2,
                            VeilingNr = 201
                        },
                        new
                        {
                            BiedNr = 1002,
                            AantalStuks = 3,
                            BedragPerFust = 21.00m,
                            GebruikerNr = 2,
                            VeilingNr = 202
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CategorieNr");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            CategorieNr = 1,
                            Naam = "Tulpen"
                        },
                        new
                        {
                            CategorieNr = 2,
                            Naam = "Rozen"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Assortiment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kvk")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LaatstIngelogd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersoneelsNr")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StraatAdres")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("GebruikerNr");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gebruiker");

                    b.HasData(
                        new
                        {
                            GebruikerNr = 1,
                            Assortiment = 12,
                            Email = "flora@example.nl",
                            Kvk = "12345678",
                            LaatstIngelogd = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Flora BV",
                            PersoneelsNr = "P1001",
                            Postcode = "1234AB",
                            Soort = "Bedrijf",
                            StraatAdres = "Bloemig 10",
                            Wachtwoord = "***"
                        },
                        new
                        {
                            GebruikerNr = 2,
                            Assortiment = 0,
                            Email = "jan@example.nl",
                            Kvk = "00000000",
                            LaatstIngelogd = new DateTime(2025, 10, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Jan Jansen",
                            PersoneelsNr = "P0000",
                            Postcode = "2345BC",
                            Soort = "Koper",
                            StraatAdres = "Laan 5",
                            Wachtwoord = "***"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Property<int>("VeilingNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Begintijd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Eindtijd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Minimumprijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("VeilingNr");

                    b.ToTable("Veiling");

                    b.HasData(
                        new
                        {
                            VeilingNr = 201,
                            Begintijd = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Minimumprijs = 10m,
                            Status = "active"
                        },
                        new
                        {
                            VeilingNr = 202,
                            Begintijd = new DateTime(2025, 10, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Eindtijd = new DateTime(2025, 10, 11, 2, 0, 0, 0, DateTimeKind.Utc),
                            Minimumprijs = 15m,
                            Status = "active"
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.Property<int>("VeilingProductNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fust")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeplaatstDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Startprijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VeilingNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voorraad")
                        .HasColumnType("INTEGER");

                    b.HasKey("VeilingProductNr");

                    b.HasIndex("VeilingNr");

                    b.HasIndex("CategorieNr", "Naam");

                    b.ToTable("Veilingproduct");

                    b.HasData(
                        new
                        {
                            VeilingProductNr = 101,
                            CategorieNr = 1,
                            Fust = 10,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Tulp Mix",
                            Startprijs = 12m,
                            VeilingNr = 201,
                            Voorraad = 500
                        },
                        new
                        {
                            VeilingProductNr = 102,
                            CategorieNr = 2,
                            Fust = 10,
                            GeplaatstDatum = new DateTime(2025, 10, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Rode Roos",
                            Startprijs = 20m,
                            VeilingNr = 202,
                            Voorraad = 300
                        });
                });

            modelBuilder.Entity("mvc_api.Models.Bieding", b =>
                {
                    b.HasOne("mvc_api.Models.Gebruiker", "Gebruiker")
                        .WithMany("Biedingen")
                        .HasForeignKey("GebruikerNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Biedingen")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("mvc_api.Models.Veilingproduct", b =>
                {
                    b.HasOne("mvc_api.Models.Categorie", "Categorie")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("CategorieNr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mvc_api.Models.Veiling", "Veiling")
                        .WithMany("Veilingproducten")
                        .HasForeignKey("VeilingNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Veiling");
                });

            modelBuilder.Entity("mvc_api.Models.Categorie", b =>
                {
                    b.Navigation("Veilingproducten");
                });

            modelBuilder.Entity("mvc_api.Models.Gebruiker", b =>
                {
                    b.Navigation("Biedingen");
                });

            modelBuilder.Entity("mvc_api.Models.Veiling", b =>
                {
                    b.Navigation("Biedingen");

                    b.Navigation("Veilingproducten");
                });
#pragma warning restore 612, 618
        }
    }
}
